let a = [
  {
    cliente: {
      nombre: 'Fundación Arco Iris',
      idcliente: '281',
      nombrecomercial: '',
      idsucursal: '256',
      sucursal: 'Sucursal Sacaba norte',
      direccion: 'C. Lopez #256, Tarata',
      nit: '328702024',
      email: 'iris@hotmail.com',
    },
    cotizacion: {
      id: '110',
      fecha: '2025-07-18',
      montototal: '21',
      descuento: '0',
    },
    divisa: { divisa: 'Dólares americanos', monedasin: '2' },
    detalle: [
      {
        id: '129',
        idproductoalmacen: '22',
        producto: 'Panetón Pandore',
        descripcion: 'en bolsa trilaminada.',
        caracteristica: '700g',
        codigoProducto: 'PP-001',
        codigoProductoSin: '991009',
        codigoActividadSin: '620100',
        unidadMedida: '17',
        codigoNandina: null,
        cantidad: '1',
        precio: '21',
      },
    ],
    usuario: { idusuario: '117', usuario: 'richard50', cargo: 'Soporte' },
    cargo: 'Soporte',
    empresa: {
      id: '50',
      nombre: 'Comercio e Inversiones YF SRL',
      celular: '+591 76548252',
      email: 'info@yofinanciero.com',
      logo: 'logos/yof_d67fc1b140.jpg',
      direccion: 'Av. Ayacucho N° 218 esq. Gral Achá',
    },
  },
]

let factura = {
  ver: 'registroVenta',
  tipoventa: '1',
  idusuario: 'eb160de1de89d9058fcb0b968dbbbd68',
  idempresa: 'c0c7c76d30bd3dcaefc96f40275bdc0a',

  idcliente: '1643',
  sucursal: '1378',

  tipodoc: '1',

  nrodoc: '00000000',

  fecha: '2025-06-30',

  puntoventa: '2',
  metodoPago: '1',
  canal: '1',
  tipopago: 'contado',

  periodopersonalizado: '0',

  jsonDetalles: {
    listaProductos: [
      {
        idproductoalmacen: '5019',
        cantidad: 1,
        precio: '12',
        idstock: '53348',
        idporcentaje: '211',
        candiponible: '1956',
        descripcion: 'Base de maquillaje completo 50 tonos',
        codigo: 'P-01',
        id: '5019',
        subtotal: 12,
        datosAdicionales: '621449-474000-47-',
      },
    ],
    listaProductosFactura: [
      {
        codigoProducto: 'P-01',
        codigoActividadSin: '474000',
        codigoProductoSin: '621449',
        descripcion: 'Base de maquillaje completo 50 tonos',
        unidadMedida: '47',
        precioUnitario: '12',
        subTotal: '12.00',
        cantidad: 1,
        numeroSerie: '',
        montoDescuento: 0,
        numeroImei: '',
        codigoNandina: '',
      },
    ],
    listaFactura: {
      numeroFactura: '',
      nombreRazonSocial: 'Cliente varios',
      codigoPuntoVenta: '2',
      fechaEmision: '2025-06-30T15:42:10.214Z',
      cafc: '',
      codigoExcepcion: '',
      descuentoAdicional: 0,
      montoGiftCard: 0,
      codigoTipoDocumentoIdentidad: '1',
      numeroDocumento: '00000000',
      complemento: '',
      codigoCliente: 'CLI_682769a09288b',
      periodoFacturado: '',
      codigoMetodoPago: 1,
      numeroTarjeta: '',
      montoTotal: '12.00',
      codigoMoneda: 2,
      montoTotalMoneda: '12.00',
      usuario: 'richard50',
      emailCliente: 'factura@yofinanciero.com',
      telefonoCliente: '0000000',
      extras: {
        facturaTicket: '',
      },
      montoTotalSujetoIva: '12.00',
      tipoCambio: 1,
      detalles: [
        {
          codigoProducto: 'P-01',
          codigoActividadSin: '474000',
          codigoProductoSin: '621449',
          descripcion: 'Base de maquillaje completo 50 tonos',
          unidadMedida: '47',
          precioUnitario: '12',
          subTotal: '12.00',
          cantidad: 1,
          numeroSerie: '',
          montoDescuento: 0,
          numeroImei: '',
          codigoNandina: '',
        },
      ],
    },
    idalmacen: '93',
    codigosinsucursal: '1',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzMDAzMzUiLCJqdGkiOiJjYjE2NDUzNTc4ZGRhYTgwNmFhMWEyNDcxMGYxZTI3OWQyODU1MGM5ZGE4MTAwNmVmNmIyYjU1YTI3MDc4ZDRjYzNjODkwZTU2NGIxZDVjNyIsImlhdCI6MTc0MjQ3NTY2NCwibmJmIjoxNzQyNDc1NjY0LCJleHAiOjE3NzQwMTE2NjQsInN1YiI6IiIsInNjb3BlcyI6W119.KFugkzjz4rXPCRsMl23sAIrDkYRuOwAJi9W0WUGg1XthO4ZvGJTsU-8ifEQYdudyIZ_b-zy49NL7fhbKoxtNVoBZbtuoYDTzCZN3Jb0Jsc3enVL_YezYr_5vA8qBBRvYdyihqTjvRQt9dYVP--QtrLp0qtQ8wP_vUyNTQh9POJUZhMd6EXjjxG_6tfgAzVOYbVty_WFU0xXDkReYLfphjqFRLPo-3vWlo5god5ixYMM55PWXLnz01bYlJREhJ-U-z46_klvgfAbdGs_EdIeBSUlYfXOn0NOWHP5Q6QlVt85ajFLByd1uv5jVW3IsDzrMkfvf1u-4YCeOkPFqU3WMvAia46nVjLnpfBNERqYEnlwmiMnNoZ2HDDiHDJyy7i8ADDGy_pS-i6SItZ6yE9Qk3MfX6xYO5bxBZXFpozSxLlVytk3qeq3tuBr9H_QXbW3G-yQzk2mHTK7iMRX8Lzm6uZuJed60MpnzekEiKQBNIWdYgp9v5BmvYHHRyvjoMn5cI2LV9RNJVKB11Z2tQHSeeY61bo9u3aGJ094v3BRpnRiIffJEP-7jo7zpvAxz3AS5bS_lFaOdfU2LboJSTAWVefTHw9JFnHnTRQZSBJ_EDqnOJrQhS6vjYa1zGtHti4Qs8U1U4cqcTn-pyzL0lqltfsdGbaBU5UE4RcsiB2eKzhs',
    tipo: '1',
    iddivisa: '9',
    idcampana: 0,
    ventatotal: '12.00',
    subtotal: '12.00',
    descuento: 0,
    nropagos: 0,
    valorpagos: 0,
    dias: null,
    fechalimite: '',
    pagosDivididos: [],
    variablePago: 'directo',
  },
}
console.log(a)
console.log(factura)
